// Barcode generation, rendering, and printing utilities for Kasi P.O.S
// Uses a self-contained Code 128B encoder — no external library required.

import { companyStore } from '@/lib/company-store';

// ─── Code 128B pattern table ──────────────────────────────────────────────────
// 107 entries (0-106). Each string is alternating bar/space widths starting bar.
// Index 103 = Start A, 104 = Start B, 105 = Start C, 106 = Stop (7 digits).

const C128: readonly string[] = [
  '212222','222122','222221','121223','121322','131222','122213','122312',
  '132212','221213','221312','231212','112232','122132','122231','113222',
  '123122','123221','223211','221132','221231','213212','223112','312131',
  '311222','321122','321221','312212','322112','322211','212123','212321',
  '232121','111323','131123','131321','112313','132113','132311','211313',
  '231113','231311','112133','112331','132131','113123','113321','133121',
  '313121','211331','231131','213113','213311','213131','311123','311321',
  '331121','312113','312311','332111','314111','221411','431111','111224',
  '111422','121124','121421','141122','141221','112214','112412','122114',
  '122411','142112','142211','241211','221114','413111','241112','134111',
  '111242','121142','121241','114212','124112','124211','411212','421112',
  '421211','212141','214121','412121','111143','111341','131141','114113',
  '114311','411113','411311','113141','114131','311141','411131',
  '211412','211214','211232', // 103=StartA  104=StartB  105=StartC
  '2331112',                   // 106=Stop
];

const START_B = 104;
const STOP    = 106;

// ─── SVG renderer ─────────────────────────────────────────────────────────────

/** Returns an inline SVG string of the Code 128B barcode for `text`. */
export function barcodeSVG(
  text:      string,
  barHeight: number  = 60,
  fontSize:  number  = 10,
  moduleW:   number  = 2,
): string {
  // Map printable ASCII (32–127) to Code 128B symbol values (0–95)
  const vals: number[] = [];
  for (const ch of text) {
    const c = ch.charCodeAt(0);
    if (c >= 32 && c <= 127) vals.push(c - 32);
  }
  if (vals.length === 0) return '';

  // Check character: (START_B + Σ position*value) mod 103
  let checksum = START_B;
  vals.forEach((v, i) => { checksum += (i + 1) * v; });
  const check = checksum % 103;

  // Build flat bar-width sequence
  const widths: number[] = [];
  const add = (idx: number) => { for (const ch of C128[idx]) widths.push(+ch); };
  add(START_B);
  vals.forEach(v => add(v));
  add(check);
  add(STOP);
  widths.push(2); // mandatory 2-module termination bar

  // SVG geometry
  const margin  = 8;
  const totalW  = widths.reduce((a, b) => a + b, 0) * moduleW + margin * 2;
  const textH   = fontSize > 0 ? fontSize + 6 : 0;
  const totalH  = barHeight + 4 + textH;

  // Build <rect> elements (even indices = bars, odd = spaces)
  let x = margin;
  let rects = '';
  widths.forEach((w, i) => {
    if (i % 2 === 0) {
      rects += `<rect x="${x}" y="2" width="${w * moduleW}" height="${barHeight}" fill="#000"/>`;
    }
    x += w * moduleW;
  });

  const textEl = fontSize > 0
    ? `<text x="${totalW / 2}" y="${barHeight + 4 + fontSize}" text-anchor="middle" ` +
      `font-family="'Courier New',monospace" font-size="${fontSize}" fill="#000" letter-spacing="1">` +
      `${svgEsc(text)}</text>`
    : '';

  return (
    `<svg xmlns="http://www.w3.org/2000/svg" width="${totalW}" height="${totalH}" ` +
    `viewBox="0 0 ${totalW} ${totalH}" style="display:block;max-width:100%">` +
    `${rects}${textEl}</svg>`
  );
}

function svgEsc(s: string): string {
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ─── Barcode value generation ─────────────────────────────────────────────────

/**
 * Derives a unique scannable barcode string from a product/service name.
 * Format: SLUG-NNNNN  e.g. BURGER-CHIPS-44291
 * All characters are Code 128B-safe (ASCII 32-127).
 */
export function generateBarcodeValue(name: string): string {
  const slug = name
    .toUpperCase()
    .replace(/[^A-Z0-9 ]/g, ' ')
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .slice(0, 3)
    .map(w => w.slice(0, 7))
    .join('-');

  const suffix = String(10000 + Math.floor(Math.random() * 90000));
  return `${slug || 'ITEM'}-${suffix}`;
}

/**
 * Returns true if the barcode was auto-generated by this system
 * (matches SLUG-NNNNN pattern with trailing 5-digit number).
 */
export function isAutoGenerated(barcode: string): boolean {
  return /^[A-Z0-9]+(-[A-Z0-9]+)*-\d{5}$/.test(barcode);
}

/**
 * Checks whether a barcode value would be a duplicate among existing barcodes.
 * Pass the current product's own barcode to exclude it from the check.
 */
export function isDuplicateBarcode(
  value: string,
  allBarcodes: string[],
  ownBarcode?: string,
): boolean {
  return allBarcodes.some(b => b === value && b !== ownBarcode);
}

// ─── Label print ──────────────────────────────────────────────────────────────

export interface LabelPrintParams {
  productName: string;
  barcode:     string;
  price?:      number;
  category?:   string;
  copies?:     number; // default 1 for thermal, 12 for A4
}

function esc(s: string | undefined | null): string {
  if (!s) return '';
  return s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;');
}

/** Builds a single thermal (58–80mm) label HTML string. */
function buildThermalLabelHTML(p: LabelPrintParams): string {
  const profile = companyStore.get();
  const shop    = profile.businessName || 'Kasi P.O.S';
  const svg     = barcodeSVG(p.barcode, 55, 9, 1.8);

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Barcode Label — ${esc(p.productName)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    @page { size: 80mm 45mm; margin: 2mm; }
    body { font-family: 'Courier New', monospace; font-size: 9pt; color: #000; background: #fff; width: 76mm; }
    .label { text-align: center; padding: 2mm 1mm; }
    .shop  { font-size: 7pt; font-weight: 700; text-transform: uppercase; letter-spacing: 1px; margin-bottom: 1mm; }
    .name  { font-size: 9pt; font-weight: 800; margin-bottom: 0.5mm; line-height: 1.2; }
    .cat   { font-size: 7pt; color: #555; margin-bottom: 1mm; }
    .price { font-size: 12pt; font-weight: 900; margin: 1mm 0; }
    .barcode { margin: 1mm auto; overflow: hidden; }
    .code  { font-size: 7pt; letter-spacing: 1.5px; margin-top: 0.5mm; }
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style>
</head>
<body>
  <div class="label">
    <div class="shop">${esc(shop)}</div>
    <div class="name">${esc(p.productName)}</div>
    ${p.category ? `<div class="cat">${esc(p.category)}</div>` : ''}
    ${p.price != null ? `<div class="price">R ${p.price.toFixed(2)}</div>` : ''}
    <div class="barcode">${svg}</div>
    <div class="code">${esc(p.barcode)}</div>
  </div>
<script>window.addEventListener('load', () => window.print());</script>
</body>
</html>`;
}

/** Builds an A4 sheet of labels (3 × 8 grid = 24 per page). */
function buildA4LabelsHTML(p: LabelPrintParams, copies = 24): string {
  const profile = companyStore.get();
  const shop    = profile.businessName || 'Kasi P.O.S';
  const svg     = barcodeSVG(p.barcode, 38, 8, 1.5);
  const count   = Math.max(1, Math.min(copies, 72));

  const cell = `
    <div class="cell">
      <div class="shop">${esc(shop)}</div>
      <div class="name">${esc(p.productName)}</div>
      ${p.category ? `<div class="cat">${esc(p.category)}</div>` : ''}
      ${p.price != null ? `<div class="price">R ${p.price.toFixed(2)}</div>` : ''}
      <div class="barcode">${svg}</div>
      <div class="code">${esc(p.barcode)}</div>
    </div>`;

  const cells = Array(count).fill(cell).join('');

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8"/>
  <title>Barcode Labels — ${esc(p.productName)}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    @page { size: A4 portrait; margin: 10mm; }
    body { font-family: Arial, sans-serif; background: #fff; color: #000; }
    .grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 4mm; }
    .cell {
      border: 0.5pt solid #ccc; border-radius: 2mm;
      padding: 2mm; text-align: center; overflow: hidden;
      page-break-inside: avoid;
    }
    .shop  { font-size: 6pt; font-weight: 700; text-transform: uppercase; letter-spacing: 0.5px; color: #555; }
    .name  { font-size: 8pt; font-weight: 800; margin: 1mm 0 0.5mm; line-height: 1.2; }
    .cat   { font-size: 6pt; color: #777; }
    .price { font-size: 10pt; font-weight: 900; margin: 1mm 0; }
    .barcode { margin: 1mm auto; overflow: hidden; }
    .code  { font-size: 6pt; letter-spacing: 1px; color: #333; margin-top: 0.5mm; font-family: 'Courier New', monospace; }
    @media print { body { -webkit-print-color-adjust: exact; print-color-adjust: exact; } }
  </style>
</head>
<body>
  <div class="grid">${cells}</div>
<script>window.addEventListener('load', () => window.print());</script>
</body>
</html>`;
}

/** Fires an iframe print of a barcode label (thermal or A4). */
export function printBarcodeLabel(params: LabelPrintParams, mode: 'thermal' | 'a4' = 'thermal'): void {
  try {
    const html = mode === 'a4'
      ? buildA4LabelsHTML(params, params.copies ?? 24)
      : buildThermalLabelHTML(params);

    const iframe = document.createElement('iframe');
    iframe.style.cssText = 'position:fixed;top:-9999px;left:-9999px;width:0;height:0;border:0;';
    document.body.appendChild(iframe);
    const doc = iframe.contentDocument ?? iframe.contentWindow?.document;
    if (!doc) { document.body.removeChild(iframe); return; }
    doc.open(); doc.write(html); doc.close();
    iframe.onload = () => {
      try { iframe.contentWindow?.focus(); iframe.contentWindow?.print(); }
      finally { setTimeout(() => { try { document.body.removeChild(iframe); } catch { /* removed */ } }, 2000); }
    };
  } catch { /* label printing must never crash the app */ }
}
