// Local state store for Kasi P.O.S (will be replaced with Lovable Cloud later)

import {
  buildSupplierRecordsFromProducts,
  mergeSupplierRecords,
  normalizeSupplierKey,
  searchSupplierRecords,
  type SupplierRecord,
} from "@/lib/supplier-directory";

export interface User {
  id: number;
  username: string;
  role: 'admin' | 'cashier';
  created_at: string;
  password_hash?: string;
}

// Deterministic password hash (synchronous, browser-safe)
export function hashPassword(plain: string): string {
  const salt = 'k@siP0S_v1_2026';
  const s = salt + plain + salt.split('').reverse().join('');
  let a = 0xdeadbeef, b = 0x41c6ce57;
  for (let i = 0; i < s.length; i++) {
    a = (Math.imul(a ^ s.charCodeAt(i), 2654435761)) >>> 0;
    b = (Math.imul(b ^ s.charCodeAt(i), 2246822519)) >>> 0;
  }
  a ^= b >>> 16; b ^= a >>> 16;
  return [(a >>> 0).toString(16).padStart(8, '0'), (b >>> 0).toString(16).padStart(8, '0')].join('');
}

export interface Supplier {
  id?: number;
  name: string;
  phone: string;
  email: string;
  address: string;
}

export interface Product {
  id: number;
  name: string;
  description: string;
  purchase_price: number;
  price: number; // selling price
  stock: number;
  stock_received: number;
  supplier: Supplier;
  barcode: string;
  image?: string;
  expiry_date?: string;
  not_expiring: boolean;
  barcode_generated?: boolean;    // true if barcode was auto-generated by the system
  barcode_created_at?: string;    // ISO timestamp when barcode was generated
  barcode_printed_count?: number; // how many times a label has been printed
}

export interface CartItem extends Product {
  quantity: number;
}

export interface Sale {
  id: number;
  total: number;
  date: string;
  cashier: string;
  items: { productId: number; name: string; quantity: number; price: number }[];
}

// Known legacy demo usernames that must never survive into production
const DEMO_USERNAMES = new Set(['admin', 'cashier1']);

// Simple localStorage-based store
function load<T>(key: string, fallback: T): T {
  try {
    const data = localStorage.getItem(`kasi_${key}`);
    return data ? JSON.parse(data) : fallback;
  } catch { return fallback; }
}

function save<T>(key: string, data: T) {
  localStorage.setItem(`kasi_${key}`, JSON.stringify(data));
}

export const store = {
  getProducts: (): Product[] => load('products', []),
  setProducts: (p: Product[]) => {
    save('products', p);
    store.syncSuppliersFromProducts(p);
  },

  getSuppliers: (): SupplierRecord[] => {
    try {
      const stored = localStorage.getItem('kasi_suppliers');
      if (stored) {
        return mergeSupplierRecords(JSON.parse(stored) as Supplier[]);
      }
    } catch {
      return buildSupplierRecordsFromProducts(store.getProducts());
    }

    const suppliers = buildSupplierRecordsFromProducts(store.getProducts());
    save('suppliers', suppliers);
    return suppliers;
  },

  setSuppliers: (suppliers: Supplier[]) => {
    save('suppliers', mergeSupplierRecords(suppliers));
  },

  syncSuppliersFromProducts: (products: Product[]) => {
    const suppliers = mergeSupplierRecords(
      store.getSuppliers(),
      products
        .map((product) => product.supplier)
        .filter((supplier): supplier is Supplier => Boolean(supplier?.name?.trim())),
    );

    save('suppliers', suppliers);
  },

  upsertSupplier: (supplier: Supplier): SupplierRecord => {
    const suppliers = mergeSupplierRecords(store.getSuppliers(), [supplier]);
    save('suppliers', suppliers);
    return suppliers.find((entry) => normalizeSupplierKey(entry.name) === normalizeSupplierKey(supplier.name))!;
  },

  getUsers: (): User[] => load('users', []),
  setUsers: (u: User[]) => save('users', u),

  getSales: (): Sale[] => load('sales', []),
  setSales: (s: Sale[]) => save('sales', s),

  getAuth: (): { username: string; role: string } | null => load('auth', null),
  setAuth: (a: { username: string; role: string } | null) => save('auth', a),

  login: (username: string, password: string): { success: boolean; role?: string } => {
    const users = load<User[]>('users', []);
    const user  = users.find(u => u.username.toLowerCase() === username.trim().toLowerCase());
    if (!user) return { success: false };
    const hashed = hashPassword(password);
    if (user.password_hash === hashed) {
      const auth = { username: user.username, role: user.role };
      save('auth', auth);
      return { success: true, role: user.role };
    }
    return { success: false };
  },

  logout: () => {
    localStorage.removeItem('kasi_auth');
  },

  // Trial management
  getTrialStart: (): string => {
    let start = localStorage.getItem('kasi_trial_start');
    if (!start) {
      start = new Date().toISOString();
      localStorage.setItem('kasi_trial_start', start);
    }
    return start;
  },

  getTrialDaysLeft: (): number => {
    const start = new Date(store.getTrialStart());
    const now = new Date();
    const elapsed = Math.floor((now.getTime() - start.getTime()) / (1000 * 60 * 60 * 24));
    return Math.max(0, 90 - elapsed);
  },

  isTrialExpired: (): boolean => {
    return store.getTrialDaysLeft() <= 0 && !store.isSubscribed();
  },

  isSubscribed: (): boolean => {
    return load('subscribed', false);
  },

  setSubscribed: (val: boolean) => {
    save('subscribed', val);
  },

  addSale: (items: CartItem[], total: number, cashier: string): number => {
    const sales = load<Sale[]>('sales', []);
    const id = sales.length > 0 ? Math.max(...sales.map(s => s.id)) + 1 : 1;
    const sale: Sale = {
      id, total, date: new Date().toISOString().slice(0, 10), cashier,
      items: items.map(i => ({ productId: i.id, name: i.name, quantity: i.quantity, price: i.price })),
    };
    sales.push(sale);
    save('sales', sales);

    // Update stock
    const products = load<Product[]>('products', []);
    items.forEach(item => {
      const p = products.find(pr => pr.id === item.id);
      if (p) p.stock = Math.max(0, p.stock - item.quantity);
    });
    save('products', products);
    return id;
  },

  // Returns true if at least one user with a real password_hash exists
  hasProductionUsers: (): boolean => {
    const users = load<User[]>('users', []);
    return users.some(u => !!u.password_hash);
  },

  // One-time migration: removes legacy demo accounts that ship with the app.
  // Real cashiers added by admin (with no password_hash) get their username as password.
  migrateFromDemo: () => {
    const raw = load<User[]>('users', []);
    if (raw.length === 0) return;

    const migrated = raw
      .filter(u => {
        if (u.password_hash) return true;                    // already a real user
        return !DEMO_USERNAMES.has(u.username.toLowerCase()); // drop demo accounts
      })
      .map(u => {
        if (!u.password_hash) {
          // Backward-compat: assign username as initial password for real cashiers
          return { ...u, password_hash: hashPassword(u.username) };
        }
        return u;
      });

    save('users', migrated);
  },

  // Supplier management
  getUniqueSuppliers: (): SupplierRecord[] => store.getSuppliers(),

  searchSuppliers: (query: string): SupplierRecord[] => {
    return searchSupplierRecords(query, store.getSuppliers());
  },

  findSupplierByName: (name: string): SupplierRecord | null => {
    const suppliers = store.getSuppliers();
    const searchName = normalizeSupplierKey(name);
    return suppliers.find((supplier) => normalizeSupplierKey(supplier.name) === searchName) || null;
  },
};
